### ISSUE TITLE
Need way to "flag" admin setting as "secret" so that it is not returned by the API

### ISSUE THREAD

**Issue by dthurston** [projectjellyfish/ux#122]
When you type in your keys for access they are not using pw fields and the text is shown in the clear.
![dashboard - jellyfish google chrome today at 5 15 49 pm](https://cloud.githubusercontent.com/assets/1986197/5928308/3a27a376-a648-11e4-84e3-31252df5a828.png)

**Comment by stackus** [comment]
The original title sounded like adding a masked field option, password inputs, was needed for several settings.

Is this still the case, or do you now want controls within UX to control if API is returning values to it and other clients?

**Comment by chriskacerguis** [comment]
Ultimately, it should be both.  Don't send it to the browser via API, and indicate via UX that it isn't being shown.
