### ISSUE TITLE
Project cards on /dashboard should indicate "pending" status

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/ux#131]
Project cards on /dashboard should indicate "pending" status

**Comment by stackus** [comment]
@chriskacerguis How would you like this status shown?

Right now there are three statuses sent to UX, I think at least one is a hold-over from the original topcoder design. Two of these values are being formatted and computed solely for UX, which means they may not have much use for other clients.

* status: raw status ok, pending, unknown, ...
* state: a formatted string of the number of problems
* state_ok: precomputed state based on the status.

**Comment by chriskacerguis** [comment]
@sonejah21 Can you please work with Stack on this?  Let him know your vision for things and he can work on this.  Please let me know if you have any questions.

**Comment by sonejah21** [comment]
@stackus - great, I'll get you the design a bit later today.

**Comment by sonejah21** [comment]
@stackus and @chriskacerguis - how many different statuses should we account for in the UX?

**Comment by chriskacerguis** [comment]
Statuses are:

Ok, Warning, Critical, Unknown/Pending
