### ISSUE TITLE
Status Update Indicator

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/ux#140]
There should be an indicator showing that actions were successfully or unsuccessful.

**Comment by OBCENEIKON** [comment]
When saving a setting in the admin panel, there would not be any feedback indicating if it was successful or not.

**Comment by gnklausner** [comment]
Currently have notifications for the following:
- *Admin Users* Create, Update, Delete (Success, Failure)
- *Admin Products* Create, Update, Delete (Success, Failure)
- *Admin Project Questions* Create, Update, Delete (Success, Failure)
- *Admin Settings* Update (Success, Failure)
- *Project* Create, Update (Success, Failure)
- *Project Service* Remove (Success, Failure)
- *Project Users* Add, Remove (Success, Failure)
- *Cart* Checkout (Success, Failure)

**Comment by OBCENEIKON** [comment]
Looks good to me, @mafernando you did the notifications backend, what do you think?

**Comment by OBCENEIKON** [comment]
Looks good to me :+1:
