### ISSUE TITLE
Fix alignment of project card icon and circles

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/ux#178]
![screen shot 2015-02-17 at 1 16 15 pm](https://cloud.githubusercontent.com/assets/9356425/6235318/41a2c198-b6a7-11e4-8a6b-d60a219a912e.png)

Project icons and circles are not aligning correctly on dashboard cards.

**Comment by mafernando** [comment]
https://github.com/projectjellyfish/ux/pull/177
Fixes project icon alignment, but project circles still need to be re-aligned.

**Comment by sonejah21** [comment]
This has been fixed with the UX refresh.
