### ISSUE TITLE
Correct CSS for project status icons

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/ux#180]
Project status icons currently use an explicit style ```box-sizing: content-box``` on each of the container <a> tags. Determine how to do this using CSS classes to be more scalable across the entire UX as opposed to this corner case.

**Comment by mafernando** [comment]
https://github.com/projectjellyfish/ux/pull/179

**Comment by mafernando** [comment]
https://github.com/projectjellyfish/ux/issues/180

**Comment by sonejah21** [comment]
This was taken care of with the ux-refresh using Twitter Bootstrap.
