### ISSUE TITLE
"Order History" table should also include "Project" column

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/ux#185]
Add column "Project" to include the project name in the Order History table.
![screen shot 2015-02-19 at 11 19 34 am](https://cloud.githubusercontent.com/assets/5269893/6271904/97841304-b829-11e4-860f-d5c31ed8d352.png)

**Comment by gnklausner** [comment]
There can be a one-to-many relationship between an order and projects. So, does it make sense to have a project column?

**Comment by chriskacerguis** [comment]
I'm not following, a project can have multiple orders, however an order CANNOT have multiple projects.

**Comment by gnklausner** [comment]
Added items to cart (note FOR PRODUCT column, which is almost certainly mislabeled): 
![projectscart1](https://cloud.githubusercontent.com/assets/9269960/6619174/e84c6626-c89e-11e4-9141-0ee1a61a0eb3.png)

Checked out cart (1 new order, namely order 14): 
![projectscart2](https://cloud.githubusercontent.com/assets/9269960/6619192/00ad9a78-c89f-11e4-9342-ce0622c29f68.png)

View of new order (Note the Project column): 
![projectscart3](https://cloud.githubusercontent.com/assets/9269960/6619201/12c37520-c89f-11e4-990d-e35668e03e3e.png)

Also, I should have said many-to-many, as you're certainly correct that a project can have multiple orders.

**Comment by sonejah21** [comment]
Looks like we have a few options: 1) Put the Project column into the table and allow for multiple projects to be listed. 2) Put the Project column into the table and if more than a certain number of Projects pertain to that order, it could say "Projects (4)" or something like this. 3) Disregard the inclusion of a Project column.

**Comment by sonejah21** [comment]
Option 1) 
![uploads/7b391f83-99e9-41d8-a65e-d9eaabc93c65/order_history_OPTION2.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7b391f83-99e9-41d8-a65e-d9eaabc93c65%2Forder_history_OPTION2.png)

**Comment by sonejah21** [comment]
Option 2)
![uploads/170ac30b-53c7-4889-b61e-7b39e04d678b/order_history-OPTION1.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F170ac30b-53c7-4889-b61e-7b39e04d678b%2Forder_history-OPTION1.png)

**Comment by sonejah21** [comment]
My thoughts are that Option 1 looks too long and cluttered. Option 2 is better, but still requires the extra click that we were trying to avoid to get all of the information on one page. Thoughts?

**Comment by sonejah21** [comment]
Optiont 3) Employing expandable rows: The user can click on the Order ID caret to see the different Projects associated, if more than one project is associated to a given Order ID.
![uploads/38099687-2313-482f-894e-25656e53b897/order_history_OPTION3.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F38099687-2313-482f-894e-25656e53b897%2Forder_history_OPTION3.png)

**Comment by sonejah21** [comment]
This is the updated styling for this ticket. 

Down the road we may want to enlist help to have the columns to the right of the multiple project orders be populated with the project's individual order details. We'd also want to consider shading these multiple project rows a darker color - like a medium gray - to set them apart from the above orders. For now I think the padding and "-" help to differentiate them to the user. 

![uploads/472cee1b-388e-45bb-ae67-e81b7a22575c/Screen Shot 2015-03-17 at 1.28.15 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F472cee1b-388e-45bb-ae67-e81b7a22575c%2FScreen+Shot+2015-03-17+at+1.28.15+PM.png)
