### ISSUE TITLE
Adjust vertical spacing: Sidebar "Order History" (too low) and "My Projects" (too high)

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/ux#187]
Adjust the spacing of the "Order History" and the "My Projects" sidebar to be vertically-centered in cells.
![uploads/4a9f4736-3b57-420e-bb48-898f9a610596/Screen Shot 2015-02-19 at 11.31.38 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4a9f4736-3b57-420e-bb48-898f9a610596%2FScreen+Shot+2015-02-19+at+11.31.38+AM.png)

**Comment by mafernando** [comment]
Should this be vertically aligned left instead of center?

**Comment by sonejah21** [comment]
If we remove the class "last" from the Order History, the padding-top is removed, centering the text vertically in its cell. Need to test to see if this affects anything else, but upon inspection it seems to do the trick. (See the line:  <a ui-sref="base.users.orders" class="li-links last" href="/users/orders"> )

**Comment by sonejah21** [comment]
/// <a u-sref="base.users.orders" class="li-links last" href="/users/orders"> ///
