### ISSUE TITLE
Need to click multiple times on Checkout button

### ISSUE THREAD

**Issue by jntullo** [projectjellyfish/ux#192]
When trying to complete an order, the "Checkout" button does not work on the first click. Usually takes multiple clicks.

**Comment by chriskacerguis** [comment]
This is due to the duplicate key issue in the sample data.

**Comment by chriskacerguis** [comment]
this was the cause:

https://github.com/projectjellyfish/api/pull/260

**Comment by chriskacerguis** [comment]
This is due to a problem with the seed file.  New seed file is needed

New seed file: https://github.com/projectjellyfish/api/issues/318
