### ISSUE TITLE
Adjust UX to use raw Twitter Bootstrap properly styled for JF

### ISSUE THREAD

**Issue by sonejah21** [projectjellyfish/ux#201]
There are three different left alignments in the "Create New Project" form. 
Adjust left margins of the form labels+fields.

![uploads/0ed8efef-d4f1-47e2-8a27-6b1f71777be6/Screen Shot 2015-02-20 at 1.17.09 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0ed8efef-d4f1-47e2-8a27-6b1f71777be6%2FScreen+Shot+2015-02-20+at+1.17.09+PM.png)

**Comment by sonejah21** [comment]
![uploads/7e5a6e9c-7c3c-4b08-aca4-2968309d07c2/Screen Shot 2015-02-20 at 1.51.53 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7e5a6e9c-7c3c-4b08-aca4-2968309d07c2%2FScreen+Shot+2015-02-20+at+1.51.53+PM.png)

**Comment by sonejah21** [comment]
This is actually a problem on many forms, so once I've fixed it I'll go through the app and add the left margin to all.

**Comment by stackus** [comment]
There are probably still some styles fighting with Bootstrap. There's styles which set something, then someone has added a class to undo it, and then added a class to redo it and so on. Class bloat is still bad but not as bad as it once was.

**Comment by sonejah21** [comment]
@stackus - thanks for the note on this, I really appreciate it! I'll have a look at the forms which are doing this correctly in order to utilize current classes.

**Comment by sonejah21** [comment]
@chriskacerguis @stackus  After working on this ticket today, I am noticing that this is quite the issue (as you mentioned, Michael). We could come up with another class and add to the complexity of the bootstrap vs existing hacks, or we can spend some time at a later date untying the knot of layered classes.  I notice the margin of 20px is being set by the "content" class, and is being reset to -15px by "row ng-scope", yet it's not straightforward to me as to how this is happening. If either of you can provide some insight, I'd appreciate it and would be happy to dig back into this.

**Comment by chriskacerguis** [comment]
@sonejah21 Let's chat about this.  I'd rather start the process to "untie the knot" now, as this will only get harder and harder as time goes by.  thoughts?

**Comment by sonejah21** [comment]
@chriskacerguis - I also think that it is important to do this the right way. I am happy to dig into it further. Let me know if you have some time to help me come up with a game plan. Until then, I'll continue to work on other tickets to stay on track. Thanks!

**Comment by chriskacerguis** [comment]
@sonejah21 can you just setup a time on my calendar for Wednesday?

**Comment by stackus** [comment]
@sonejah21 So part of that knot is classes like 'content' which try to do things that Bootstrap already gives you. The 'row ng-scope' classes you saw were, minus ng-scope which is part of Angular and can be ignored, is Bootstrap.

Part of the knot are the multiple nested elements that wrap the main content area, of which I think there's a main-content, content, main-container, and container classes. The main content area should have a 'containter-fluid' class at it's root and then most actual content should be in 'row's.

Seeing nested elements with ng-scope, ng-* are OK even if they appear with to just exist to nest only one element. This again is Angular's nested scope at work. There should never be a class associated with any of these elements and I don't think I've seen any.

The first step to cleaning up the views is to remove nesting elements that exist with 'content', 'main-content', 'box-content', and replace them with a single 'container-fluid' and 'row' combination element across the various templates. I'd prefer to cull classes that exist in _screen_old.sass as much as possible.

**Comment by chriskacerguis** [comment]
Looking into the complexity of this.  Might need to strip out the current look, switch to raw twitter bootstrap, then re-theme to match existing look.  Need to review with @chrishample

**Comment by sonejah21** [comment]
Working on new Twitter bootstrap pages now to handle this problem and other styling issues the team has been having.
