### ISSUE TITLE
My Projects Spacing Issue

### ISSUE THREAD

**Issue by gnklausner** [projectjellyfish/ux#217]
There's a spacing issue when you open up a project. The caret drops to a new line.
![sidebarspacingissue](https://cloud.githubusercontent.com/assets/9269960/6380732/b46305e0-bd09-11e4-891c-903f0e5b8bc8.jpg)

**Comment by chriskacerguis** [comment]
Dup of https://github.com/projectjellyfish/ux/issues/186

Closing.
