### ISSUE TITLE
Floating Point Error in Cart

### ISSUE THREAD

**Issue by gnklausner** [projectjellyfish/ux#227]
Not sure if it's caused by the addition or the multiplication, but something goes awry: 
![floatingpointerror](https://cloud.githubusercontent.com/assets/9269960/6415565/dd87d86e-be6d-11e4-8102-b61128b3f373.png)

**Comment by gnklausner** [comment]
It has to be the addition, seeing that the error is introduced when calculating the sum of the column.

**Comment by stackus** [comment]
There's an angular filter 'currency' that formats values into USD.

https://docs.angularjs.org/api/ng/filter/currency

**Comment by gnklausner** [comment]
Is there an upper limit we can assume for how much precision a price will require? For example, a large EC2 requires thousandths of a dollar.

**Comment by chriskacerguis** [comment]
I would go with 0.0000 (no more than that).
