### ISSUE TITLE
Products cannot be added currently.

### ISSUE THREAD

**Issue by brittballard** [projectjellyfish/ux#268]
https://huboard.com/projectjellyfish/api/#/issues/60234959

**Comment by brittballard** [comment]
I've attached two images to the ticket in API that demonstrate the error. I think there maybe issues in both UX and API on this one.

**Comment by mafernando** [comment]
The Create/Update methods have been moved out of the ProductsController into the ManageIqProductsController.

UX is currently expecting Create/Update methods defined on Products Controller which is causing an

AbstractController::ActionNotFound (The action 'create' could not be found for ProductsController):

error to be thrown.

Figure out a way to resolve this.

**Comment by brittballard** [comment]
This should be fixed now. With the stuff merged earlier.
