### ISSUE TITLE
Alert dialog needs to scroll

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/ux#299]
Alert dialog needs to scroll
![screen shot 2015-03-19 at 10 40 58 am](https://cloud.githubusercontent.com/assets/2414647/6736827/7eb89f3c-ce24-11e4-9d63-44f5be73d954.png)

**Comment by gnklausner** [comment]
Just to clarify, do we want scroll or do we want auto-fit? We currently limit it to 5 alerts (which, now that I think about it, may not be a good idea).

**Comment by chriskacerguis** [comment]
scroll.
